//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotRS.Tools.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotRS.Tools.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument not provided.
        /// </summary>
        internal static string ARGUEMENTNOTPROVIDED {
            get {
                return ResourceManager.GetString("ARGUEMENTNOTPROVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CleanupJsonConfig extension cannot handle Chained configurations..
        /// </summary>
        internal static string CANNOTHANDLECHAINEDCONFIGURATIONS {
            get {
                return ResourceManager.GetString("CANNOTHANDLECHAINEDCONFIGURATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns in unexpected order.
        /// </summary>
        internal static string COLUMNSINUNEXPECTEDORDER {
            get {
                return ResourceManager.GetString("COLUMNSINUNEXPECTEDORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename was not found the the Content-Disposition.
        /// </summary>
        internal static string FILENAMENOTINCONTENTDISPOSITION {
            get {
                return ResourceManager.GetString("FILENAMENOTINCONTENTDISPOSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to form-data.
        /// </summary>
        internal static string FORMDATA {
            get {
                return ResourceManager.GetString("FORMDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodName cannot be null or whitespace.
        /// </summary>
        internal static string METHODNAMECANNOTBENULL {
            get {
                return ResourceManager.GetString("METHODNAMECANNOTBENULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing content-type boundary..
        /// </summary>
        internal static string MISSINGCONTETETYPEBOUNDARY {
            get {
                return ResourceManager.GetString("MISSINGCONTETETYPEBOUNDARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no way to &apos;unobfuscate&apos; a value, therefore there is no reason to implement the ReadJson method..
        /// </summary>
        internal static string NOUNOBFUSCATE {
            get {
                return ResourceManager.GetString("NOUNOBFUSCATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is null.
        /// </summary>
        internal static string NULLPARAMETER {
            get {
                return ResourceManager.GetString("NULLPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obfuscated.
        /// </summary>
        internal static string OBFUSCATED {
            get {
                return ResourceManager.GetString("OBFUSCATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object provided is not an Enum..
        /// </summary>
        internal static string OBJNOTPROVIDEDTOENUM {
            get {
                return ResourceManager.GetString("OBJNOTPROVIDEDTOENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response has already started, the http status code middleware will not be executed..
        /// </summary>
        internal static string RESPONSEALREADYSTARTED {
            get {
                return ResourceManager.GetString("RESPONSEALREADYSTARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the given value is not an enumeration..
        /// </summary>
        internal static string TYPENOTINASSEMBLY {
            get {
                return ResourceManager.GetString("TYPENOTINASSEMBLY", resourceCulture);
            }
        }
    }
}
